### ISSUE TITLE
Implement Actions for package submission PRs

### ISSUE THREAD

**Issue by federico-terzi** [espanso/hub#1]
This new package system strives to accomplish these goals:
* The package submission process should be easy for contributors
* The verification process should be easy for maintainers

# New package format

In its basic form, a package is composed of 3 files:

* A `_manifest.yml` file containing the package metadata:

```yml
name: "dummy-package"
title: "Dummy package"
description: A dummy package for testing
version: 0.1.0
author: Federico Terzi
```

* A `README.md` file containing the package description (and documentation, if necessary)
* The `package.yml` file, which contains the actual snippets:

```yaml
matches:
  - trigger: ":hello"
    replace: "world"
```

These three files MUST be present in each package, but the package might also contain other files, such as other `yml` files containing more snippets.

To recap, the package directory content should be:

```
_manifest.yml
README.md
package.yml
```

# Checks

In order to maintain a good quality while minimizing the amount of time spent by maintainers to keep the hub running, it's critical that we implement a series of automated checks that verify PRs against a set of basic rules.

**These should run on each submitted PR, as well as each repository push.** The goal is to always keep the repository consistent and to be notified when something is off.

Each of the following sections describes a check that we should implement through a Github Actions job.

## Naming convention

Package names should be only composed of alphanumeric characters and the hyphen `-` character. For example:

* `best-emojis` and `emojis123` are valid names
* `best_emojis` and `best@emojis` are not.

NOTE: this should also be enforced at the _path_ level, meaning that the name should follow this convention both in the `_manifest.yml` file and in the actual package structure, as described in the "Path coherence" section below.

## Manifest format

Each `_manifest.yml` file MUST contain the following fields: `name`, `title`, `description`, `version` and `author`. If any of them is missing, the check should fail.

## Required files

Each package directory MUST contain the `_manifest.yml`, `README.md` and `package.yml` files. The check should fail if any of these files is missing, but packages can include other additional files.

## Path coherence

Packages should follow a standard format and location. For example, a package named `best-emojis` and having version `0.1.1` should be located in the `packages/best-emojis/0.1.1/...` directory

If a package has multiple versions, we should follow this structure:

```
packages/
  best-emojis/
    0.1.0/
      _manifest.yml
      ...
    0.1.1/
      _manifest.yml
      ...
```

**This path should be coherent with the contents of the `_manifest.yml` file, in particular, the `name` and `version` attributes of the manifest should reflect the actual path structure**.

## YAML syntax

All YAML files contained by a package should be valid YAML. Therefore, we should always attempt to parse each `.yml` and `.yaml` file and fail if a syntax error is present.

**Comment by 4lch4** [comment]
I posted this in Discord but figure it'd be helpful to have here as well:

I'm curious why the manifest starts with an underscore instead of just simply `manifest.yaml|yml`. I feel like there's gotta be a reason and I'm just not seeing it.

**Comment by federico-terzi** [comment]
> I'm curious why the manifest starts with an underscore instead of just simply manifest.yaml|yml. I feel like there's gotta be a reason and I'm just not seeing it.

@4lch4 You are absolutely right! I still haven't got the chance to write a proper documentation on the new v2 format, but the reason is that espanso now automatically reads every `.yml` file in the configuration directory **unless it starts with an underscore**.

For this reason, starting the manifest with an underscore avoids the automatic loading process without creating any particular edge-case in the config loading logic :)

**Comment by federico-terzi** [comment]
Thanks to the help of @4lch4, we now have a starting point :) https://github.com/4lch4/Espanso-Validator

**Comment by federico-terzi** [comment]
@Mte90 Yes :)

We can close this now, thank you for the help!

**Comment by Mte90** [comment]
There is a documentation page about it?
