### ISSUE TITLE
How to test packages I am writing

### ISSUE THREAD

**Issue by lizard-heart** [espanso/hub#12]
Hello,

I have been making a package following the steps in the documentation (I forked and cloned this repo, duplicated the dummy folder, wrote stuff in the `package.yaml` file, etc. ) and I want to be able to test out my package as I am writing it. I tried simply dragging the folder to the directory with all my installed packages (`/Library/Preferences/espanso/packages`) but it is not showing up. Thanks!

**Comment by federico-terzi** [comment]
Hey @lizard-heart,

I'm sorry you experienced this problem! Could you please try renaming the package file to `package.yml` (not `.yaml`) and see if that helps?

We'll definitely need to improve the experience, please bear with us in the meanwhile :)

Cheers :)

**Comment by lizard-heart** [comment]
Sorry, it is a `.yml` file. I just made a typo. It's possible I'm just making some other silly mistake, but if there is some solution let me know.

**Comment by federico-terzi** [comment]
@lizard-heart What version of espanso are you using? (you can find out by running `espanso --version`) :)

**Comment by lizard-heart** [comment]
espanso 0.7.3

**Comment by IdiosApps** [comment]
@lizard-heart which OS is this on? 

On Windows, I can show Espanso logs. It may clarify where package are being read from.
![image](https://user-images.githubusercontent.com/12559216/177422167-d83b7e39-6264-41f5-918a-ba4b12a230e3.png)

Let's say I make a change to `C:\Users\IdiosApps\AppData\Roaming\espanso\match\packages\espanso-translate-en-zh.yml` and save it.

Espanso will hot-reload the change:
![image](https://user-images.githubusercontent.com/12559216/177422445-4bd8d4ca-d482-404d-a61e-9f6d717fcf36.png)

and my match works: zero:zh -> {〇}(líng)[zero]

**Comment by smeech** [comment]
Is this issue still current (it's been a while) or shall we close it?

**Comment by smeech** [comment]
I'll close this old Issue, but will happily reopen it if it's still a problem.
