### ISSUE TITLE
Display source link for all open-source packages

### ISSUE THREAD

**Issue by hmnd** [espanso/hub#2]
It's currently difficult to find the source of a package without manually searching for it yourself. Thus, it would be great if there was a link back to the source listed on every package's page. It would also help users with being able to trust that the package they are installing is safe.

**Comment by federico-terzi** [comment]
Hey @hmnd,

Thank you for the feedback! Your point is indeed very good, we should make the package source easier to access for end-users!
We'll make sure to add this feature in the next iteration of the hub :)

Cheers :)

**Comment by smeech** [comment]
If a user puts a `homepage:` link in their `_manifest.yml` the hub provides a link, but it's an [option](https://espanso.org/docs/packages/package-specification/#the-_manifestyml-file).

**Comment by smeech** [comment]
If a user puts a `homepage:` link in their `_manifest.yml` the hub provides a link to that, but it's an [option](https://espanso.org/docs/packages/package-specification/#the-_manifestyml-file).
Additonally, the `package.yml` is now displayed in the hub's page for the package.
