### ISSUE TITLE
Update Actions to notify frontend app on a new release

### ISSUE THREAD

**Issue by arabello** [espanso/hub#23]
To trigger a new deployment of the [frontend application](https://github.com/espanso/hub-frontend), the `publish-packages` workflow should send a [`repository_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch) event to the [frontend repo webhook](https://api.github.com/repos/espanso/hub-frontend/dispatches).

For example, via [`curl`](https://github.community/t/triggering-by-other-repository/16163/2) as an additional step after publishing the packages.

The JSON data to be posted has to follow the below schema:
```
{
   "event_type": "new-hub-release",
   "client_payload":{
      "PACKAGE_INDEX_URL": $newPackageIndexUrl
   }
}
```

A personal access token with `repo` permissions is required to perform the webhook call successfully.

**Comment by IdiosApps** [comment]
Is this issue redundant now, after this PR? https://github.com/espanso/hub/pull/28

**Comment by arabello** [comment]
Yes, the mechanism is already implemented and working. Closing this.
