### ISSUE TITLE
Auto generate PR to hub when a new release is avalaible

### ISSUE THREAD

**Issue by Mte90** [espanso/hub#65]
It is very boring for a new update do a new PR everytime manually creates everything etc and the documentation doesn't help with something automatic.

**Comment by smeech** [comment]
Thank you for your suggestion. I am sorry it has taken so long to reply.

As it would be all too easy for someone deliberately or inadvertently to introduce dangerous code with an update, we decided against automatic updates to ensure they are all reviewed for safety, I'm afraid.

As this is an old Issue, I'd be inclined to close it unless someone thinks of a safe way of implementing it.
